export type ChallengeType = "drag-drop-ipo" | "drag-drop-classify" | "ordering" | "matching" | "calculation";

export interface Challenge {
  id: string;
  sector: string;
  company: string;
  type: ChallengeType;
  difficulty: "easy" | "medium" | "hard";
  points: number;
  role: string;
  scenario: string;
  mission: string;
  explanation: string;
  items?: { id: string; text: string; category: string }[];
  steps?: { id: string; text: string; order: number }[];
  pairs?: { id: string; left: string; right: string }[];
  calcData?: { prompt: string; hints: string[]; answer: number; unit: string; tolerance: number };
  correctAnswer: any;
}

export const businessCases = {
  netflix: {
    name: "Netflix",
    sector: "Entertainment & Media",
    description: "Content Delivery Platform serving 300M+ subscribers globally",
    icon: "N",
    color: "bg-red-500",
  },
  spotify: {
    name: "Spotify",
    sector: "Music Streaming",
    description: "AI-powered music recommendation platform with 600M+ users",
    icon: "S",
    color: "bg-green-500",
  },
  grab: {
    name: "Grab",
    sector: "Mobility & Super-app",
    description: "Southeast Asia's ride-hailing and delivery super-app",
    icon: "G",
    color: "bg-emerald-600",
  },
  shopify: {
    name: "Shopify",
    sector: "E-commerce Platform",
    description: "E-commerce platform powering 5.6M+ merchant stores",
    icon: "Sh",
    color: "bg-purple-500",
  },
  airbnb: {
    name: "Airbnb",
    sector: "Hospitality & Sharing Economy",
    description: "Two-sided marketplace connecting hosts and guests globally",
    icon: "A",
    color: "bg-pink-500",
  },
};

export const challenges: Challenge[] = [
  // ═══════════════════════════════════════════════════════
  // NETFLIX
  // ═══════════════════════════════════════════════════════
  {
    id: "netflix-1",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Junior Data Analyst",
    scenario: "It's your first week at Netflix. Your manager asks you to map the content delivery system using the IPO framework. Drag each component into the correct category.",
    mission: "Sort these Netflix components into Input, Processing, or Output.",
    items: [
      { id: "n1", text: "User viewing history and preferences", category: "input" },
      { id: "n2", text: "Live event camera feeds via AWS", category: "input" },
      { id: "n3", text: "Cloud-based video transcoding", category: "processing" },
      { id: "n4", text: "Open Connect CDN (17,000+ servers)", category: "processing" },
      { id: "n5", text: "300M+ subscribers streaming content", category: "output" },
      { id: "n6", text: "Personalized 'Top 10' recommendations", category: "output" },
    ],
    correctAnswer: { input: ["n1", "n2"], processing: ["n3", "n4"], output: ["n5", "n6"] },
    explanation: "User data and camera feeds are Inputs entering the system. Transcoding and CDN distribution are Processing that transforms content. Subscriber streaming and personalized lists are the Outputs delivered to users.",
  },
  {
    id: "netflix-2",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Infrastructure Intern",
    scenario: "You're touring Netflix's live streaming infrastructure during a major boxing event. Map each element of the live pipeline to the IPO model.",
    mission: "Classify each live streaming component as Input, Processing, or Output.",
    items: [
      { id: "nl1", text: "Raw camera feeds from the arena", category: "input" },
      { id: "nl2", text: "Viewer device bandwidth data", category: "input" },
      { id: "nl3", text: "AWS MediaLive encoding streams", category: "processing" },
      { id: "nl4", text: "Adaptive bitrate algorithm", category: "processing" },
      { id: "nl5", text: "100M+ concurrent device streams", category: "output" },
      { id: "nl6", text: "Real-time quality dashboard", category: "output" },
    ],
    correctAnswer: { input: ["nl1", "nl2"], processing: ["nl3", "nl4"], output: ["nl5", "nl6"] },
    explanation: "Raw feeds and device data are Inputs. Encoding and adaptive algorithms are Processing. The concurrent streams and dashboards are Outputs — the value delivered.",
  },
  {
    id: "netflix-3",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Platform Reliability Engineer",
    scenario: "You need to document Netflix's content delivery pipeline from start to finish. The steps are jumbled — put them in the correct order.",
    mission: "Arrange the content delivery pipeline in the correct sequence.",
    steps: [
      { id: "ns1", text: "Content creators upload raw video files", order: 1 },
      { id: "ns2", text: "Videos transcoded into multiple quality levels in cloud", order: 2 },
      { id: "ns3", text: "Encoded content distributed to Open Connect CDN servers", order: 3 },
      { id: "ns4", text: "User requests stream; device capabilities detected", order: 4 },
      { id: "ns5", text: "Adaptive bitrate delivers optimal quality to viewer", order: 5 },
    ],
    correctAnswer: ["ns1", "ns2", "ns3", "ns4", "ns5"],
    explanation: "The IPO pipeline flows: raw upload (Input) → cloud transcoding → CDN distribution (Processing) → user request → adaptive delivery (Output). Each stage transforms data from the previous one.",
  },
  {
    id: "netflix-4",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Digital Strategy Consultant",
    scenario: "You're auditing Netflix's technology stack for an investor report. Classify each component correctly.",
    mission: "Drag each item into Digital Tool, Digital Technology, or Business Concept.",
    items: [
      { id: "nc1", text: "AWS MediaLive (live ingest service)", category: "tool" },
      { id: "nc2", text: "Open Connect Appliances (OCAs)", category: "tool" },
      { id: "nc3", text: "Cloud computing infrastructure", category: "technology" },
      { id: "nc4", text: "Multi-region content replication", category: "technology" },
      { id: "nc5", text: "Network effects from subscriber growth", category: "business" },
      { id: "nc6", text: "Cost reduction via owned CDN", category: "business" },
    ],
    correctAnswer: { tool: ["nc1", "nc2"], technology: ["nc3", "nc4"], business: ["nc5", "nc6"] },
    explanation: "Tools are specific software/hardware (MediaLive, OCAs). Technologies are broad paradigms (cloud, replication). Business Concepts are strategic models (network effects, cost savings).",
  },
  {
    id: "netflix-5",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Systems Architect",
    scenario: "You're presenting Netflix's architecture to the CTO. Connect each component on the left to its correct IPO classification and description on the right.",
    mission: "Draw connections between each Netflix component and its correct classification.",
    pairs: [
      { id: "nm1", left: "38M events/second monitoring data", right: "Input: Raw data collected from platform" },
      { id: "nm2", left: "Apache Kafka event streaming", right: "Processing: Real-time data transformation" },
      { id: "nm3", left: "Open Connect CDN caching layer", right: "Processing: Content distribution to edge" },
      { id: "nm4", left: "Subscriber streaming experience", right: "Output: Value delivered to users" },
      { id: "nm5", left: "User content preferences", right: "Input: User-generated behavioral data" },
    ],
    correctAnswer: { nm1: "nm1", nm2: "nm2", nm3: "nm3", nm4: "nm4", nm5: "nm5" },
    explanation: "Monitoring data and user preferences are Inputs (raw data). Kafka streaming and CDN caching are Processing (transformation/distribution). The streaming experience is Output (value delivered).",
  },
  {
    id: "netflix-6",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "VP of Infrastructure Strategy",
    scenario: "Netflix serves 300 million subscribers globally. During peak evening hours, 5% of all subscribers stream simultaneously. Each concurrent stream requires 5 Mbps of bandwidth.",
    mission: "Calculate the total peak bandwidth Netflix needs in Terabits per second (Tbps).",
    calcData: {
      prompt: "Total peak bandwidth needed",
      hints: ["300M subscribers x 5% = concurrent streams", "Concurrent streams x 5 Mbps = total Mbps", "Divide by 1,000,000 to convert Mbps to Tbps"],
      answer: 75,
      unit: "Tbps",
      tolerance: 2,
    },
    correctAnswer: 75,
    explanation: "300M x 5% = 15M concurrent streams. 15M x 5 Mbps = 75,000,000 Mbps = 75 Tbps. This massive bandwidth requirement is why Netflix built Open Connect — to reduce dependency on third-party CDNs.",
  },

  // ═══════════════════════════════════════════════════════
  // SPOTIFY
  // ═══════════════════════════════════════════════════════
  {
    id: "spotify-1",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "ML Product Manager",
    scenario: "You've joined Spotify's recommendation team. Map the recommendation system components to the IPO framework.",
    mission: "Sort these Spotify components into Input, Processing, or Output.",
    items: [
      { id: "s1", text: "User listening history (plays, skips, saves)", category: "input" },
      { id: "s2", text: "Audio files with 12 sonic metrics", category: "input" },
      { id: "s3", text: "Collaborative filtering algorithms", category: "processing" },
      { id: "s4", text: "CNN-based audio analysis engine", category: "processing" },
      { id: "s5", text: "Discover Weekly personalized playlist", category: "output" },
      { id: "s6", text: "AI DJ with personalized narration", category: "output" },
    ],
    correctAnswer: { input: ["s1", "s2"], processing: ["s3", "s4"], output: ["s5", "s6"] },
    explanation: "User behavior and audio files are Inputs. Collaborative filtering and CNN analysis are Processing algorithms. Discover Weekly and AI DJ are Outputs — personalized value delivered to users.",
  },
  {
    id: "spotify-2",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "User Experience Researcher",
    scenario: "You're studying how Spotify's playlist generation pipeline works. Classify each step in the pipeline.",
    mission: "Categorize each playlist generation element as Input, Processing, or Output.",
    items: [
      { id: "sp1", text: "User's saved songs and playlists", category: "input" },
      { id: "sp2", text: "Blog posts and reviews about music (NLP source)", category: "input" },
      { id: "sp3", text: "BaRT reinforcement learning system", category: "processing" },
      { id: "sp4", text: "NLP analysis of music metadata", category: "processing" },
      { id: "sp5", text: "Daily Mix personalized playlists", category: "output" },
      { id: "sp6", text: "Release Radar weekly new music", category: "output" },
    ],
    correctAnswer: { input: ["sp1", "sp2"], processing: ["sp3", "sp4"], output: ["sp5", "sp6"] },
    explanation: "Saved songs and external text data are Inputs. BaRT and NLP are Processing algorithms. Daily Mix and Release Radar are Outputs — curated music experiences.",
  },
  {
    id: "spotify-3",
    sector: "Music Streaming",
    company: "Spotify",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Artist Growth Strategist",
    scenario: "A new Thai artist uploaded their first song with zero streams. Arrange how Spotify's cold-start system discovers and recommends the song.",
    mission: "Put the cold-start recommendation process in the correct order.",
    steps: [
      { id: "ss1", text: "New song uploaded to Spotify with metadata", order: 1 },
      { id: "ss2", text: "CNN analyzes audio for 12 sonic features (tempo, energy, mood)", order: 2 },
      { id: "ss3", text: "NLP processes song title, genre tags, and artist bio", order: 3 },
      { id: "ss4", text: "System matches sonic profile with similar-taste user clusters", order: 4 },
      { id: "ss5", text: "Song appears in Discover Weekly for matched users", order: 5 },
    ],
    correctAnswer: ["ss1", "ss2", "ss3", "ss4", "ss5"],
    explanation: "The cold-start pipeline: song upload (Input) → audio analysis + NLP (Processing) → user matching (Processing) → playlist placement (Output). This solves the problem of recommending songs with zero listening data.",
  },
  {
    id: "spotify-4",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Technical Documentation Lead",
    scenario: "You're writing Spotify's internal glossary. Classify each element into the correct category.",
    mission: "Drag each item into Digital Tool, Digital Technology, or Business Concept.",
    items: [
      { id: "sc1", text: "Spotify mobile app and web player", category: "tool" },
      { id: "sc2", text: "Spotify for Artists dashboard", category: "tool" },
      { id: "sc3", text: "Convolutional Neural Networks (CNN)", category: "technology" },
      { id: "sc4", text: "Natural Language Processing (NLP)", category: "technology" },
      { id: "sc5", text: "Data-driven personalization strategy", category: "business" },
      { id: "sc6", text: "Freemium-to-premium conversion model", category: "business" },
    ],
    correctAnswer: { tool: ["sc1", "sc2"], technology: ["sc3", "sc4"], business: ["sc5", "sc6"] },
    explanation: "Tools are user-facing software (app, dashboard). Technologies are AI/ML paradigms (CNN, NLP). Business Concepts are strategic models (personalization, freemium).",
  },
  {
    id: "spotify-5",
    sector: "Music Streaming",
    company: "Spotify",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "AI Research Engineer",
    scenario: "Match each ML technique Spotify uses to its specific function in the recommendation pipeline.",
    mission: "Connect each technology on the left to its correct function on the right.",
    pairs: [
      { id: "sm1", left: "Collaborative Filtering", right: "Finds users with similar taste patterns" },
      { id: "sm2", left: "CNN Audio Analysis", right: "Extracts sonic features from raw audio" },
      { id: "sm3", left: "NLP Text Mining", right: "Analyzes blog posts and reviews about music" },
      { id: "sm4", left: "BaRT Reinforcement Learning", right: "Optimizes recommendation strategies over time" },
      { id: "sm5", left: "Audio Feature Extraction", right: "Measures tempo, energy, danceability metrics" },
    ],
    correctAnswer: { sm1: "sm1", sm2: "sm2", sm3: "sm3", sm4: "sm4", sm5: "sm5" },
    explanation: "Each ML technique serves a distinct role: collaborative filtering matches user tastes, CNN processes audio signals, NLP mines text, BaRT optimizes decisions, and feature extraction quantifies sonic properties.",
  },
  {
    id: "spotify-6",
    sector: "Music Streaming",
    company: "Spotify",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Chief Product Officer",
    scenario: "Spotify has 600 million total users. 40% are monthly active users. Each active user streams an average of 25 songs per day.",
    mission: "Calculate the total number of daily streams in millions.",
    calcData: {
      prompt: "Total daily streams",
      hints: ["600M users x 40% = monthly active users", "Active users x 25 songs/day = total daily streams"],
      answer: 6000,
      unit: "million streams",
      tolerance: 50,
    },
    correctAnswer: 6000,
    explanation: "600M x 40% = 240M active users. 240M x 25 = 6,000M daily streams. This massive volume of Input data is what feeds Spotify's Processing algorithms to generate personalized Output playlists.",
  },

  // ═══════════════════════════════════════════════════════
  // GRAB
  // ═══════════════════════════════════════════════════════
  {
    id: "grab-1",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Operations Trainee",
    scenario: "You're shadowing a Grab operations manager in Bangkok. Map the ride-hailing system to the IPO framework.",
    mission: "Sort these Grab ride-hailing components into Input, Processing, or Output.",
    items: [
      { id: "g1", text: "Passenger ride request with pickup/dropoff", category: "input" },
      { id: "g2", text: "Driver GPS location data", category: "input" },
      { id: "g3", text: "Real-time driver-rider matching algorithm", category: "processing" },
      { id: "g4", text: "Route optimization engine", category: "processing" },
      { id: "g5", text: "Completed ride with fare payment", category: "output" },
      { id: "g6", text: "Trip receipt and driver rating prompt", category: "output" },
    ],
    correctAnswer: { input: ["g1", "g2"], processing: ["g3", "g4"], output: ["g5", "g6"] },
    explanation: "Ride requests and GPS data are Inputs. Matching and routing algorithms are Processing. Completed rides and receipts are Outputs — the delivered value.",
  },
  {
    id: "grab-2",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Product Manager",
    scenario: "Grab's super-app spans rides, food, and payments. Map the food delivery flow to IPO.",
    mission: "Classify each GrabFood component as Input, Processing, or Output.",
    items: [
      { id: "gf1", text: "Customer food order and preferences", category: "input" },
      { id: "gf2", text: "Restaurant menu data and availability", category: "input" },
      { id: "gf3", text: "Order assignment and prep-time estimation", category: "processing" },
      { id: "gf4", text: "Delivery route and ETA calculation", category: "processing" },
      { id: "gf5", text: "Food delivered to customer's door", category: "output" },
      { id: "gf6", text: "Order confirmation with live tracking", category: "output" },
    ],
    correctAnswer: { input: ["gf1", "gf2"], processing: ["gf3", "gf4"], output: ["gf5", "gf6"] },
    explanation: "Customer orders and restaurant data are Inputs. Assignment algorithms and route planning are Processing. Delivered food and tracking are Outputs.",
  },
  {
    id: "grab-3",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Algorithm Engineer",
    scenario: "When a passenger requests a ride, multiple steps happen in rapid sequence. Arrange the complete ride flow in order.",
    mission: "Put the Grab ride-hailing flow in the correct sequence.",
    steps: [
      { id: "gs1", text: "Passenger enters pickup location and destination", order: 1 },
      { id: "gs2", text: "Algorithm evaluates 50+ nearby drivers in real-time", order: 2 },
      { id: "gs3", text: "Optimal driver assigned based on distance and rating", order: 3 },
      { id: "gs4", text: "Driver navigates to pickup using optimized route", order: 4 },
      { id: "gs5", text: "Ride completed, payment processed via GrabPay", order: 5 },
    ],
    correctAnswer: ["gs1", "gs2", "gs3", "gs4", "gs5"],
    explanation: "The flow follows IPO: passenger request (Input) → algorithm evaluation and assignment (Processing) → navigation and completion (Output). Each step builds on the previous.",
  },
  {
    id: "grab-4",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Technology Auditor",
    scenario: "You're auditing Grab's platform for an investor report. Classify each component correctly.",
    mission: "Drag each item into Digital Tool, Digital Technology, or Business Concept.",
    items: [
      { id: "gc1", text: "Grab mobile app for riders/drivers", category: "tool" },
      { id: "gc2", text: "GrabPay digital wallet", category: "tool" },
      { id: "gc3", text: "Real-time GPS tracking system", category: "technology" },
      { id: "gc4", text: "Cloud infrastructure for scalability", category: "technology" },
      { id: "gc5", text: "Two-sided marketplace model", category: "business" },
      { id: "gc6", text: "Cross-service ecosystem integration", category: "business" },
    ],
    correctAnswer: { tool: ["gc1", "gc2"], technology: ["gc3", "gc4"], business: ["gc5", "gc6"] },
    explanation: "Tools are specific apps (Grab app, GrabPay). Technologies are broad capabilities (GPS, cloud). Business Concepts are strategic models (marketplace, ecosystem).",
  },
  {
    id: "grab-5",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Business Strategy Director",
    scenario: "Connect each Grab service to the business concept it demonstrates.",
    mission: "Draw connections between each service and its matching business concept.",
    pairs: [
      { id: "gm1", left: "GrabCar ride-hailing", right: "Two-sided marketplace (riders and drivers)" },
      { id: "gm2", left: "GrabFood delivery", right: "Platform extension into adjacent markets" },
      { id: "gm3", left: "GrabPay digital wallet", right: "Financial ecosystem lock-in" },
      { id: "gm4", left: "GrabMart grocery delivery", right: "Horizontal diversification" },
      { id: "gm5", left: "GrabRewards loyalty program", right: "Customer retention via incentives" },
    ],
    correctAnswer: { gm1: "gm1", gm2: "gm2", gm3: "gm3", gm4: "gm4", gm5: "gm5" },
    explanation: "Each Grab service demonstrates a distinct business concept: marketplace dynamics, market extension, financial lock-in, diversification, and retention strategies.",
  },
  {
    id: "grab-6",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Chief Technology Officer",
    scenario: "Grab has 200 million registered users across 8 countries. 30% are weekly active users. Each active user makes an average of 2 trips per week.",
    mission: "Calculate the total number of weekly trips in millions.",
    calcData: {
      prompt: "Total weekly trips",
      hints: ["200M users x 30% = weekly active users", "Active users x 2 trips/week = total weekly trips"],
      answer: 120,
      unit: "million trips",
      tolerance: 5,
    },
    correctAnswer: 120,
    explanation: "200M x 30% = 60M active users. 60M x 2 = 120M weekly trips. This volume of Input (ride requests) flows through Processing (matching algorithms) to produce Output (completed trips).",
  },

  // ═══════════════════════════════════════════════════════
  // SHOPIFY
  // ═══════════════════════════════════════════════════════
  {
    id: "shopify-1",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Merchant Success Specialist",
    scenario: "A small business owner just signed up for Shopify. Map the platform's e-commerce components to the IPO framework.",
    mission: "Sort these Shopify components into Input, Processing, or Output.",
    items: [
      { id: "sh1", text: "Merchant product listings and photos", category: "input" },
      { id: "sh2", text: "Customer orders and payment info", category: "input" },
      { id: "sh3", text: "Ruby on Rails app across 100+ pods", category: "processing" },
      { id: "sh4", text: "66 million Kafka messages per second", category: "processing" },
      { id: "sh5", text: "40,000 checkouts per minute (peak)", category: "output" },
      { id: "sh6", text: "$292.3B in GMV processed annually", category: "output" },
    ],
    correctAnswer: { input: ["sh1", "sh2"], processing: ["sh3", "sh4"], output: ["sh5", "sh6"] },
    explanation: "Merchant data and customer orders are Inputs. The Rails infrastructure and Kafka messaging are Processing. Checkout volume and GMV are Outputs — measurable value delivered.",
  },
  {
    id: "shopify-2",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Financial Analyst",
    scenario: "Map the Black Friday checkout flow to the IPO model.",
    mission: "Classify each Black Friday system element as Input, Processing, or Output.",
    items: [
      { id: "sb1", text: "Customer browsing and cart selections", category: "input" },
      { id: "sb2", text: "Payment card details and billing address", category: "input" },
      { id: "sb3", text: "Fraud detection and payment verification", category: "processing" },
      { id: "sb4", text: "Inventory check and order routing", category: "processing" },
      { id: "sb5", text: "Order confirmation email to customer", category: "output" },
      { id: "sb6", text: "Shipping label generated for fulfillment", category: "output" },
    ],
    correctAnswer: { input: ["sb1", "sb2"], processing: ["sb3", "sb4"], output: ["sb5", "sb6"] },
    explanation: "Cart selections and payment details are Inputs. Fraud detection and routing are Processing. Confirmations and shipping labels are Outputs.",
  },
  {
    id: "shopify-3",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Site Reliability Engineer",
    scenario: "During Black Friday, an order flows through Shopify's distributed system. Arrange the processing pipeline in order.",
    mission: "Put the order processing steps in the correct sequence.",
    steps: [
      { id: "so1", text: "Customer clicks 'Buy Now' on merchant store", order: 1 },
      { id: "so2", text: "Request routed to appropriate pod via load balancer", order: 2 },
      { id: "so3", text: "Inventory verified and payment authorized", order: 3 },
      { id: "so4", text: "Order data published to Kafka for downstream services", order: 4 },
      { id: "so5", text: "Confirmation sent to customer; fulfillment triggered", order: 5 },
    ],
    correctAnswer: ["so1", "so2", "so3", "so4", "so5"],
    explanation: "The pipeline: customer action (Input) → routing → verification → message distribution (Processing) → confirmation and fulfillment (Output). The pod architecture enables this at 284M requests/minute.",
  },
  {
    id: "shopify-4",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Data Pipeline Engineer",
    scenario: "Classify Shopify's platform elements for an architecture review.",
    mission: "Drag each item into Digital Tool, Digital Technology, or Business Concept.",
    items: [
      { id: "scc1", text: "Shopify Markets app (international selling)", category: "tool" },
      { id: "scc2", text: "Shopify POS (point-of-sale system)", category: "tool" },
      { id: "scc3", text: "Distributed pod architecture (100+ pods)", category: "technology" },
      { id: "scc4", text: "Apache Kafka event streaming", category: "technology" },
      { id: "scc5", text: "Reducing barriers for small merchants", category: "business" },
      { id: "scc6", text: "Platform-as-a-service revenue model", category: "business" },
    ],
    correctAnswer: { tool: ["scc1", "scc2"], technology: ["scc3", "scc4"], business: ["scc5", "scc6"] },
    explanation: "Tools are specific applications (Markets, POS). Technologies are architectural paradigms (pod architecture, Kafka). Business Concepts are strategic approaches (barrier reduction, PaaS model).",
  },
  {
    id: "shopify-5",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Quality Assurance Director",
    scenario: "Match each Shopify architecture component to its role in the system.",
    mission: "Connect each component to its correct description.",
    pairs: [
      { id: "smm1", left: "MySQL databases (per pod)", right: "Persistent storage for merchant/order data" },
      { id: "smm2", left: "Redis cache layer", right: "Fast in-memory data access for hot queries" },
      { id: "smm3", left: "Kafka messaging system", right: "Asynchronous event routing between services" },
      { id: "smm4", left: "Load balancer", right: "Distributes incoming traffic across pods" },
      { id: "smm5", left: "Memcached layer", right: "Caches frequently accessed objects to reduce DB load" },
    ],
    correctAnswer: { smm1: "smm1", smm2: "smm2", smm3: "smm3", smm4: "smm4", smm5: "smm5" },
    explanation: "Each component serves a distinct infrastructure role: MySQL for persistence, Redis for fast access, Kafka for event routing, load balancer for traffic distribution, Memcached for object caching.",
  },
  {
    id: "shopify-6",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "International Expansion Manager",
    scenario: "Shopify has 5.6 million merchants worldwide. Each merchant has an average of 50 products listed on their store.",
    mission: "Calculate the total number of product listings (Inputs) on the platform in millions.",
    calcData: {
      prompt: "Total product listings on Shopify",
      hints: ["5.6M merchants x 50 products each", "This represents the total Input data volume"],
      answer: 280,
      unit: "million listings",
      tolerance: 10,
    },
    correctAnswer: 280,
    explanation: "5.6M x 50 = 280M product listings. These listings are all Inputs to the Shopify platform that must be processed (indexed, rendered, searched) to create the Output (functional online stores with checkout capability).",
  },

  // ═══════════════════════════════════════════════════════
  // AIRBNB
  // ═══════════════════════════════════════════════════════
  {
    id: "airbnb-1",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Host Relations Coordinator",
    scenario: "A new host in Chiang Mai just listed their Lanna-style house. Map Airbnb's marketplace components to IPO.",
    mission: "Sort these Airbnb components into Input, Processing, or Output.",
    items: [
      { id: "a1", text: "8M+ property listings from hosts worldwide", category: "input" },
      { id: "a2", text: "Guest search queries and date preferences", category: "input" },
      { id: "a3", text: "Search ranking and matching algorithms", category: "processing" },
      { id: "a4", text: "Microservices architecture on AWS", category: "processing" },
      { id: "a5", text: "Confirmed bookings with secure payments", category: "output" },
      { id: "a6", text: "Trust & safety verification results", category: "output" },
    ],
    correctAnswer: { input: ["a1", "a2"], processing: ["a3", "a4"], output: ["a5", "a6"] },
    explanation: "Listings and search queries are Inputs. Algorithms and infrastructure are Processing. Bookings and verification are Outputs — the value created by the marketplace.",
  },
  {
    id: "airbnb-2",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Payment Systems Analyst",
    scenario: "A Tokyo guest books a Bali villa. Map the booking transaction flow to IPO.",
    mission: "Classify each booking flow element as Input, Processing, or Output.",
    items: [
      { id: "ab1", text: "Guest's selected dates and guest count", category: "input" },
      { id: "ab2", text: "Host's pricing rules and availability calendar", category: "input" },
      { id: "ab3", text: "Price calculation with fees and currency conversion", category: "processing" },
      { id: "ab4", text: "Identity verification and fraud detection", category: "processing" },
      { id: "ab5", text: "Booking confirmation sent to host and guest", category: "output" },
      { id: "ab6", text: "Payment held in escrow until check-in", category: "output" },
    ],
    correctAnswer: { input: ["ab1", "ab2"], processing: ["ab3", "ab4"], output: ["ab5", "ab6"] },
    explanation: "Guest selections and host pricing are Inputs. Calculation and verification are Processing. Confirmation and payment escrow are Outputs.",
  },
  {
    id: "airbnb-3",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Growth Strategy Analyst",
    scenario: "Arrange the guest journey from initial search to post-stay review on Airbnb.",
    mission: "Put the complete Airbnb guest journey in the correct order.",
    steps: [
      { id: "as1", text: "Guest searches for accommodation with filters", order: 1 },
      { id: "as2", text: "Algorithm ranks listings by relevance and quality", order: 2 },
      { id: "as3", text: "Guest selects listing and submits booking request", order: 3 },
      { id: "as4", text: "Payment processed and host notified", order: 4 },
      { id: "as5", text: "Guest completes stay and leaves review", order: 5 },
    ],
    correctAnswer: ["as1", "as2", "as3", "as4", "as5"],
    explanation: "The journey maps to IPO: search input → algorithmic processing (ranking) → booking selection → payment processing → review output. The review then becomes Input for future guests, creating a feedback loop.",
  },
  {
    id: "airbnb-4",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Cloud Infrastructure Architect",
    scenario: "Classify Airbnb's platform components for an architecture presentation.",
    mission: "Drag each item into Digital Tool, Digital Technology, or Business Concept.",
    items: [
      { id: "ac1", text: "Airbnb mobile app and website", category: "tool" },
      { id: "ac2", text: "Secure payment processing system", category: "tool" },
      { id: "ac3", text: "AWS cloud infrastructure", category: "technology" },
      { id: "ac4", text: "Microservices architecture", category: "technology" },
      { id: "ac5", text: "Two-sided marketplace model", category: "business" },
      { id: "ac6", text: "Trust through community ratings", category: "business" },
    ],
    correctAnswer: { tool: ["ac1", "ac2"], technology: ["ac3", "ac4"], business: ["ac5", "ac6"] },
    explanation: "Tools are user-facing applications (app, payment system). Technologies are infrastructure paradigms (cloud, microservices). Business Concepts are strategic models (marketplace, trust).",
  },
  {
    id: "airbnb-5",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Trust & Safety Director",
    scenario: "Match each trust system component to the layer it belongs to.",
    mission: "Connect each trust component to its correct classification layer.",
    pairs: [
      { id: "am1", left: "Review and rating interface in app", right: "Digital Tool: User-facing feature" },
      { id: "am2", left: "SSL encryption for payments", right: "Digital Technology: Security protocol" },
      { id: "am3", left: "ID verification algorithm", right: "Digital Technology: Identity processing" },
      { id: "am4", left: "Community trust driving bookings", right: "Business Concept: Competitive advantage" },
      { id: "am5", left: "Host Superhost badge program", right: "Business Concept: Quality incentive" },
    ],
    correctAnswer: { am1: "am1", am2: "am2", am3: "am3", am4: "am4", am5: "am5" },
    explanation: "The trust system spans all three layers: Tools (review interface), Technologies (encryption, ID verification), and Business Concepts (community trust, quality incentives). Real platforms require all three layers working together.",
  },
  {
    id: "airbnb-6",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Competitive Intelligence Analyst",
    scenario: "Airbnb has 8 million property listings worldwide. The average occupancy rate is 50%, and listings are available 365 days per year.",
    mission: "Calculate the total guest-nights booked per year in millions.",
    calcData: {
      prompt: "Total annual guest-nights",
      hints: ["8M listings x 50% occupancy rate", "Multiply by 365 days per year", "Express answer in millions"],
      answer: 1460,
      unit: "million guest-nights",
      tolerance: 50,
    },
    correctAnswer: 1460,
    explanation: "8M x 50% x 365 = 1,460M guest-nights per year. Each booking is an Output of the platform, generated from host listing Inputs processed through Airbnb's matching and transaction Processing systems.",
  },
];
