export interface Challenge {
  id: string;
  sector: string;
  company: string;
  type: "multiple-choice";
  difficulty: "easy" | "medium" | "hard";
  points: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export const businessCases = {
  netflix: {
    name: "Netflix",
    sector: "Entertainment & Media",
    description: "Content Delivery Platform serving 300M+ subscribers globally",
    icon: "N",
    color: "bg-red-500",
  },
  spotify: {
    name: "Spotify",
    sector: "Music Streaming",
    description: "AI-powered music recommendation platform with 600M+ users",
    icon: "S",
    color: "bg-green-500",
  },
  grab: {
    name: "Grab",
    sector: "Mobility & Super-app",
    description: "Southeast Asia's ride-hailing and delivery super-app",
    icon: "G",
    color: "bg-emerald-600",
  },
  shopify: {
    name: "Shopify",
    sector: "E-commerce Platform",
    description: "E-commerce platform powering 5.6M+ merchant stores",
    icon: "Sh",
    color: "bg-purple-500",
  },
  airbnb: {
    name: "Airbnb",
    sector: "Hospitality & Sharing Economy",
    description: "Two-sided marketplace connecting hosts and guests globally",
    icon: "A",
    color: "bg-pink-500",
  },
};

export const challenges: Challenge[] = [
  // ── NETFLIX (6 questions) ──────────────────────────────────

  {
    id: "netflix-1",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "In the IPO model for Netflix's content delivery, which of the following is an INPUT?",
    options: [
      "300M+ subscribers streaming content simultaneously",
      "Open Connect CDN distributing video to edge servers",
      "User viewing data and content preferences collected from the platform",
      "Personalized recommendation lists shown on the homepage",
    ],
    correctAnswer: 2,
    explanation: "User viewing data and preferences are collected as INPUT. The CDN is Processing, and subscriber streaming and recommendation lists are Outputs.",
  },
  {
    id: "netflix-2",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "Netflix's Open Connect CDN uses 17,000+ servers placed inside ISP networks worldwide. In the IPO framework, this CDN is best classified as:",
    options: [
      "An Input because it collects data from users",
      "A Processing component because it transforms and distributes content closer to users",
      "An Output because it is the final product users see",
      "Neither Input, Processing, nor Output",
    ],
    correctAnswer: 1,
    explanation: "The Open Connect CDN is a Processing component. It takes encoded content (input) and distributes/caches it across edge servers to reduce latency, transforming how content reaches the viewer.",
  },
  {
    id: "netflix-3",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Netflix processes 38 million events per second for real-time monitoring. Which digital technology enables this massive-scale event processing?",
    options: [
      "Traditional SQL databases with scheduled batch queries",
      "Event streaming platforms such as Apache Kafka combined with real-time analytics engines",
      "Email notification systems and manual spreadsheets",
      "Desktop applications storing data on local hard drives",
    ],
    correctAnswer: 1,
    explanation: "Netflix uses event streaming platforms (Apache Kafka, Mantis, Druid) to process 38M events/second in real-time, enabling immediate monitoring and decision-making across its live streaming infrastructure.",
  },
  {
    id: "netflix-4",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "AWS MediaLive is used by Netflix for live broadcast ingest. How should AWS MediaLive be classified?",
    options: [
      "A Digital Technology, because it represents a broad computing paradigm",
      "A Business Concept, because it drives revenue growth",
      "A Digital Tool, because it is a specific software service used to perform a particular task",
      "An Output, because it produces the final user experience",
    ],
    correctAnswer: 2,
    explanation: "AWS MediaLive is a Digital Tool -- a specific, named software service that performs the concrete task of ingesting live broadcast feeds. Digital Technologies are broader paradigms (e.g., cloud computing), while Business Concepts focus on strategy and economics.",
  },
  {
    id: "netflix-5",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Netflix built its own CDN (Open Connect) instead of renting third-party CDN services. What Business Concept does this decision primarily demonstrate?",
    options: [
      "Network effects from subscriber growth",
      "Cost reduction and vertical integration by owning critical infrastructure",
      "Data-driven personalization of content",
      "Two-sided marketplace dynamics between creators and viewers",
    ],
    correctAnswer: 1,
    explanation: "By building Open Connect, Netflix vertically integrated its delivery infrastructure, achieving significant cost reduction (the business concept). This is distinct from network effects (value from more users) or personalization (algorithmic recommendations).",
  },
  {
    id: "netflix-6",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Consider the full IPO flow of Netflix live streaming: live camera feeds enter the system, get transcoded in the cloud, distributed via CDN, and reach 100M concurrent devices. Which statement correctly maps the entire flow?",
    options: [
      "Input: transcoded video; Processing: camera feeds; Output: CDN servers",
      "Input: live camera feeds and user preferences; Processing: cloud transcoding and CDN distribution; Output: streaming experience on 100M+ concurrent devices",
      "Input: CDN edge servers; Processing: user preferences; Output: live camera feeds",
      "Input: 100M devices; Processing: live camera feeds; Output: cloud transcoding",
    ],
    correctAnswer: 1,
    explanation: "The correct IPO mapping is: Input (raw live feeds + user data) -> Processing (cloud transcoding + CDN distribution) -> Output (seamless streaming on 100M+ concurrent devices). Each stage transforms the previous one.",
  },

  // ── SPOTIFY (6 questions) ──────────────────────────────────

  {
    id: "spotify-1",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "In Spotify's recommendation system, user listening behavior (play history, skips, saves) is best classified as:",
    options: [
      "An Output because it represents user actions on the platform",
      "Processing because the data is being generated in real-time",
      "An Input because this data feeds into the recommendation algorithms",
      "A Digital Tool because it is a specific software feature",
    ],
    correctAnswer: 2,
    explanation: "User listening behavior is an Input -- it is the raw data that feeds into Spotify's recommendation algorithms. The algorithms process this input, and the personalized playlists are the output.",
  },
  {
    id: "spotify-2",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "Spotify's 'Discover Weekly' personalized playlist, generated every Monday for each user, is best classified as:",
    options: [
      "An Input because users listen to it",
      "Processing because it involves complex algorithms",
      "An Output because it is the value delivered to the user after algorithmic processing",
      "A Digital Technology because it uses machine learning",
    ],
    correctAnswer: 2,
    explanation: "Discover Weekly is an Output -- it is the end result delivered to users after Spotify's algorithms (Processing) analyze listening data (Input). It represents the value the platform creates.",
  },
  {
    id: "spotify-3",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Spotify uses three pillars for recommendations: collaborative filtering, NLP, and CNN audio analysis. What business concept does this multi-layered approach primarily demonstrate?",
    options: [
      "Cost minimization through simple, single-algorithm processing",
      "Data-driven personalization to maximize user engagement and retention",
      "Manual curation by human music editors",
      "Random song selection to ensure equal exposure for all artists",
    ],
    correctAnswer: 1,
    explanation: "Spotify's multi-layered ML approach demonstrates data-driven personalization -- a business concept that maximizes user engagement by combining multiple data sources and algorithms to create highly relevant, individualized recommendations.",
  },
  {
    id: "spotify-4",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Spotify's BaRT (Bandits for Recommendations as Treatments) is a reinforcement learning system. In the IPO model, BaRT is classified as:",
    options: [
      "An Input because it collects data from users",
      "A Processing component because it is an algorithm that transforms input data into recommendations",
      "An Output because users interact with its results",
      "A Business Concept because it drives engagement metrics",
    ],
    correctAnswer: 1,
    explanation: "BaRT is a Processing component -- it is an algorithm (reinforcement learning) that takes user behavior data (Input) and generates optimized recommendations (Output). The algorithm itself sits in the Processing layer.",
  },
  {
    id: "spotify-5",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "A new artist uploads their first song to Spotify with zero streams. How does Spotify solve this 'cold start' problem to recommend the song to relevant listeners?",
    options: [
      "Spotify waits until the song reaches 1,000 streams before including it in recommendations",
      "The song is shown only to users who already follow the artist on social media",
      "Spotify uses CNN-based audio analysis to understand sonic features, plus NLP on metadata, enabling recommendations before any streaming data exists",
      "The song is randomly shown to all 600M+ users equally until enough data accumulates",
    ],
    correctAnswer: 2,
    explanation: "Spotify solves the cold start problem by analyzing the actual audio (CNN models extract sonic features) and processing metadata via NLP. This allows the system to match the song with users who enjoy similar-sounding music, even with zero play history.",
  },
  {
    id: "spotify-6",
    sector: "Music Streaming",
    company: "Spotify",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Spotify analyzes audio files across 12 sonic metrics (tempo, energy, danceability, etc.) using Convolutional Neural Networks. Which classification is correct?",
    options: [
      "CNN is a Digital Tool; audio analysis is a Business Concept; the 12 metrics are Outputs",
      "CNN is a Digital Technology; the audio analysis algorithm is Processing; the 12 sonic metrics are Inputs to the recommendation engine",
      "CNN is a Business Concept; audio files are Processing; sonic metrics are Digital Tools",
      "CNN is an Output; audio files are Digital Technologies; sonic metrics are Inputs",
    ],
    correctAnswer: 1,
    explanation: "CNN (Convolutional Neural Network) is a Digital Technology -- a broad AI/ML paradigm. The audio analysis algorithm is Processing (transforming raw audio into structured data). The 12 sonic metrics extracted become Inputs to the downstream recommendation engine.",
  },

  // ── GRAB (6 questions) ──────────────────────────────────

  {
    id: "grab-1",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "When a passenger opens Grab and requests a ride, what does this ride request represent in the IPO model?",
    options: [
      "Processing, because the app is calculating the fare",
      "Output, because the passenger has completed an action",
      "Input, because the request is data entering the platform that triggers further processing",
      "A Digital Tool, because the Grab app is software",
    ],
    correctAnswer: 2,
    explanation: "A ride request is an Input -- it is user-generated data entering the platform. The matching algorithm (Processing) then uses this input along with driver location data to produce a driver assignment (Output).",
  },
  {
    id: "grab-2",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "Grab's real-time matching algorithm pairs riders with nearby drivers. In the IPO framework, this algorithm is:",
    options: [
      "An Input because it receives location data",
      "Processing because it transforms ride requests and driver locations into optimal driver assignments",
      "An Output because it produces a matched driver",
      "A Business Concept because it creates marketplace efficiency",
    ],
    correctAnswer: 1,
    explanation: "The matching algorithm is Processing -- it takes inputs (ride request + driver GPS locations) and transforms them into an optimal assignment. The assigned driver notification is the Output.",
  },
  {
    id: "grab-3",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Grab operates as a 'super-app' combining ride-hailing, food delivery, and digital payments (GrabPay). What business concept does this strategy demonstrate?",
    options: [
      "Specialization in a single core service to reduce complexity",
      "Ecosystem integration creating cross-service network effects where each service strengthens the others",
      "Outsourcing all operations to independent third-party vendors",
      "Geographic limitation to a single country for focused growth",
    ],
    correctAnswer: 1,
    explanation: "Grab's super-app strategy demonstrates ecosystem integration -- combining multiple services creates cross-service network effects. Ride users discover food delivery, food users adopt GrabPay, and GrabPay users try more services, creating a self-reinforcing growth cycle.",
  },
  {
    id: "grab-4",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "GrabPay (digital wallet) and the Grab mobile app are both part of the platform. How should each be classified?",
    options: [
      "Both are Digital Technologies because they use advanced computing",
      "Both are Business Concepts because they generate revenue",
      "Both are Digital Tools -- specific software applications that users interact with directly to perform tasks",
      "GrabPay is a Digital Technology; the mobile app is a Business Concept",
    ],
    correctAnswer: 2,
    explanation: "Both GrabPay and the Grab mobile app are Digital Tools -- they are specific, user-facing software applications designed for particular tasks (payments and ride-booking). Digital Technologies (e.g., GPS, cloud computing) are the broader technical capabilities they rely on.",
  },
  {
    id: "grab-5",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Grab serves 200M users across 8 Southeast Asian countries with ride-hailing, food delivery, and financial services. Which statement correctly maps its complete IPO flow?",
    options: [
      "Input: completed rides; Processing: customer payments; Output: ride requests",
      "Input: ride/food requests, driver GPS, restaurant menus; Processing: matching algorithms, route optimization, payment processing; Output: completed rides, delivered food, financial transactions",
      "Input: matching algorithms; Processing: ride requests; Output: driver GPS data",
      "Input: GrabPay wallet; Processing: mobile app; Output: driver location",
    ],
    correctAnswer: 1,
    explanation: "The complete IPO flow: Inputs (requests, location data, menus) are transformed by Processing (algorithms, optimization, payment engines) into Outputs (completed services, deliveries, transactions). Each layer clearly transforms the previous one.",
  },
  {
    id: "grab-6",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Grab uses real-time GPS tracking and cloud infrastructure for scalability. How should these be classified compared to the 'two-sided marketplace' model?",
    options: [
      "GPS and cloud are Business Concepts; two-sided marketplace is a Digital Technology",
      "GPS and cloud are Digital Tools; two-sided marketplace is Processing",
      "GPS and cloud are Digital Technologies (broad technical capabilities); two-sided marketplace is a Business Concept (strategic model for value creation)",
      "All three are Digital Technologies because they involve computing",
    ],
    correctAnswer: 2,
    explanation: "GPS tracking and cloud computing are Digital Technologies -- broad technical capabilities that enable the platform. The two-sided marketplace is a Business Concept -- a strategic model describing how the platform creates value by connecting riders/eaters with drivers/restaurants.",
  },

  // ── SHOPIFY (6 questions) ──────────────────────────────────

  {
    id: "shopify-1",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "On Shopify's platform, merchants upload product listings, photos, and inventory data. In the IPO model, this merchant data is:",
    options: [
      "Processing, because Shopify transforms it into a storefront",
      "Output, because it becomes visible on the online store",
      "Input, because it is raw data entering the platform that will be processed and displayed",
      "A Business Concept, because it represents commerce activity",
    ],
    correctAnswer: 2,
    explanation: "Merchant product listings and inventory data are Inputs -- raw data entering the Shopify platform. Processing transforms this data (organizing, indexing, rendering), and the resulting online store experience is the Output.",
  },
  {
    id: "shopify-2",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "Shopify processed $292.3B in Gross Merchandise Value (GMV) annually and handles 40,000 checkouts per minute during peak sales. These metrics represent:",
    options: [
      "Inputs because they measure what enters the system",
      "Processing because they describe how the system works",
      "Outputs because they represent the value and transactions delivered by the platform",
      "Digital Technologies because they involve large-scale computing",
    ],
    correctAnswer: 2,
    explanation: "$292.3B GMV and 40,000 checkouts/minute are Outputs -- they are the measurable results of the platform's processing. They represent the value delivered to merchants and customers.",
  },
  {
    id: "shopify-3",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Shopify uses a modular pod architecture with 100+ isolated instances, each having dedicated MySQL, Redis, and Memcached. What digital technology concept does this architecture represent?",
    options: [
      "Monolithic architecture where all components share a single database",
      "Distributed systems architecture enabling independent scaling and fault isolation",
      "Client-side computing where all processing happens in the browser",
      "Manual server management without any automation",
    ],
    correctAnswer: 1,
    explanation: "Shopify's 100+ isolated pods represent distributed systems architecture. Each pod can scale independently and if one fails, others continue operating. This prevents single points of failure and enables massive scalability (284M requests/minute during Black Friday).",
  },
  {
    id: "shopify-4",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Shopify processes 66 million Kafka messages per second. In the IPO framework, this message processing layer is classified as:",
    options: [
      "Input, because messages are data entering the system",
      "Processing, because Kafka transforms, routes, and manages the flow of data between system components",
      "Output, because the messages reach their destination",
      "A Digital Tool, because Kafka is a named software product",
    ],
    correctAnswer: 1,
    explanation: "The Kafka message processing layer is Processing -- it transforms, routes, and manages data flow between Shopify's distributed components. While Kafka itself is a Digital Tool, its role in the system architecture is Processing. The question asks about the processing layer, not the tool classification.",
  },
  {
    id: "shopify-5",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Shopify Markets increased cross-border transactions by 97% for small businesses by enabling international selling. Which combination correctly identifies the three layers involved?",
    options: [
      "Digital Tool: marketing campaigns; Digital Technology: email; Business Concept: local selling only",
      "Digital Tool: Shopify Markets app; Digital Technology: automated currency conversion and localization; Business Concept: marketplace expansion reducing entry barriers for small merchants",
      "Digital Tool: spreadsheets; Digital Technology: manual translation; Business Concept: limiting to domestic sales",
      "Digital Tool: physical stores; Digital Technology: paper invoices; Business Concept: avoiding international markets",
    ],
    correctAnswer: 1,
    explanation: "International selling requires all three layers: Digital Tool (Shopify Markets app -- the specific software), Digital Technology (automated currency conversion, payment processing, localization -- the technical capabilities), and Business Concept (marketplace expansion strategy reducing barriers for small merchants).",
  },
  {
    id: "shopify-6",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "During Black Friday 2025, Shopify handled 284 million requests per minute. Consider the full IPO flow: merchant data and customer orders enter the system, are processed through 100+ pods with Kafka messaging, and result in completed checkouts. Which element is NOT correctly classified?",
    options: [
      "Customer payment information is an Input (correct classification)",
      "Ruby on Rails application with 100+ pods is Processing (correct classification)",
      "Completed checkout transactions are Outputs (correct classification)",
      "Merchant product listings are Processing (INCORRECT -- they are actually Inputs)",
    ],
    correctAnswer: 3,
    explanation: "Merchant product listings are Inputs, not Processing. They are raw data entering the system. Processing is what Shopify does with that data (indexing, rendering, transaction handling). The question tests whether you can identify the misclassification.",
  },

  // ── AIRBNB (6 questions) ──────────────────────────────────

  {
    id: "airbnb-1",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "Airbnb hosts submit 8M+ property listings with photos, descriptions, pricing, and availability calendars. In the IPO model, these listings are:",
    options: [
      "Processing, because hosts actively manage them",
      "Output, because guests can view them on the platform",
      "Input, because they are data entering the platform that will be processed, ranked, and matched with guest searches",
      "A Business Concept, because they represent the sharing economy",
    ],
    correctAnswer: 2,
    explanation: "Property listings are Inputs -- they are data contributed by hosts that enter the platform. Airbnb's search algorithms (Processing) then rank and match these listings with guest queries to produce search results and bookings (Output).",
  },
  {
    id: "airbnb-2",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "easy",
    points: 100,
    question: "When a guest completes a booking on Airbnb with confirmed payment, this confirmed booking is best classified as:",
    options: [
      "An Input because it generates data for the platform",
      "Processing because payment involves complex computation",
      "An Output because it is the value delivered -- the successful transaction resulting from matching hosts with guests",
      "A Digital Technology because it uses encryption",
    ],
    correctAnswer: 2,
    explanation: "A confirmed booking with payment is an Output -- it is the final value delivered by the platform. Host listings and guest searches (Inputs) were processed through matching algorithms (Processing) to produce this result.",
  },
  {
    id: "airbnb-3",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Airbnb's platform value increases as more hosts join (more choices for guests), which attracts more guests (more revenue for hosts), which then attracts even more hosts. What business concept describes this cycle?",
    options: [
      "Linear growth where each new user adds a fixed amount of value",
      "Network effects creating a self-reinforcing positive feedback loop",
      "Fixed marketplace where value remains constant regardless of participants",
      "Competition between hosts that reduces overall platform value",
    ],
    correctAnswer: 1,
    explanation: "This describes network effects -- a business concept where platform value increases exponentially as more participants join. Each new host makes the platform more valuable for guests, and vice versa, creating a self-reinforcing growth cycle.",
  },
  {
    id: "airbnb-4",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "medium",
    points: 150,
    question: "Airbnb runs on AWS cloud infrastructure using a microservices architecture. How should these two elements be classified?",
    options: [
      "AWS is a Digital Tool; microservices is a Business Concept",
      "Both are Digital Technologies -- broad technical paradigms that enable the platform's scalability and reliability",
      "AWS is a Business Concept; microservices is an Output",
      "Both are Digital Tools -- specific named products for performing tasks",
    ],
    correctAnswer: 1,
    explanation: "Both AWS cloud infrastructure and microservices architecture are Digital Technologies -- they are broad technical paradigms (cloud computing, distributed architecture) that enable Airbnb's platform to scale. AWS as a specific service could also be seen as a tool, but architecturally these represent technology paradigms.",
  },
  {
    id: "airbnb-5",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Airbnb's trust system uses ratings, reviews, identity verification, and secure payments. Consider: the Airbnb app is a Digital Tool, the payment encryption is a Digital Technology, and 'trust through community ratings' is a Business Concept. Which statement is correct?",
    options: [
      "The trust system is purely a Digital Technology because it uses algorithms",
      "The trust system is purely a Digital Tool because it is software",
      "The trust system spans all three layers: the app (Tool) provides the interface, encryption (Technology) secures data, and community trust (Business Concept) creates marketplace confidence",
      "The trust system is only a Business Concept because it is about reputation",
    ],
    correctAnswer: 2,
    explanation: "Airbnb's trust system spans all three layers: Digital Tools (the app interface for leaving reviews), Digital Technologies (encryption, identity verification algorithms), and Business Concepts (community-driven trust as a competitive advantage). Real-world systems often span multiple categories.",
  },
  {
    id: "airbnb-6",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "multiple-choice",
    difficulty: "hard",
    points: 200,
    question: "Consider Airbnb's complete IPO flow: host listings and guest searches enter the platform, search/ranking algorithms on AWS microservices process the data, and confirmed bookings with trust verification are delivered. A competitor launches with identical technology but no existing users. Why does Airbnb maintain its advantage?",
    options: [
      "Because Airbnb has better server hardware (a technology advantage)",
      "Because Airbnb's mobile app has a better user interface (a tool advantage)",
      "Because Airbnb has accumulated network effects -- 8M+ listings and millions of reviews create value that new technology alone cannot replicate (a business concept advantage)",
      "Because Airbnb uses a different programming language (a technology advantage)",
    ],
    correctAnswer: 2,
    explanation: "Airbnb's competitive moat is the Business Concept of network effects. With 8M+ listings, millions of reviews, and established trust, new competitors cannot replicate this value with technology alone. This demonstrates why Business Concepts (network effects, trust) can be more defensible than Digital Tools or Technologies.",
  },
];
