export type ChallengeType = "drag-drop-ipo" | "drag-drop-classify" | "ordering" | "matching" | "calculation";

export interface Challenge {
  id: string;
  sector: string;
  company: string;
  type: ChallengeType;
  difficulty: "easy" | "medium" | "hard";
  points: number;
  role: string;
  scenario: string;
  mission: string;
  explanation: string;
  items?: { id: string; text: string; category: string }[];
  steps?: { id: string; text: string; order: number }[];
  pairs?: { id: string; left: string; right: string }[];
  calcData?: { prompt: string; hints: string[]; answer: number; unit: string; tolerance: number };
  correctAnswer: any;
}

export const AVATARS = [
  { id: "ninja", emoji: "\u{1F977}", name: "Ninja" },
  { id: "astronaut", emoji: "\u{1F468}\u200D\u{1F680}", name: "Astronaut" },
  { id: "wizard", emoji: "\u{1F9D9}", name: "Wizard" },
  { id: "robot", emoji: "\u{1F916}", name: "Robot" },
  { id: "fox", emoji: "\u{1F98A}", name: "Fox" },
  { id: "dragon", emoji: "\u{1F409}", name: "Dragon" },
  { id: "unicorn", emoji: "\u{1F984}", name: "Unicorn" },
  { id: "detective", emoji: "\u{1F575}\uFE0F", name: "Detective" },
];

export const businessCases = {
  netflix: {
    name: "Netflix",
    sector: "Entertainment & Media",
    description: "The world's biggest streaming service",
    icon: "N",
    color: "bg-red-500",
    emoji: "\u{1F3AC}",
    questName: "Streaming Kingdom",
  },
  spotify: {
    name: "Spotify",
    sector: "Music Streaming",
    description: "The music app that knows your taste",
    icon: "S",
    color: "bg-green-500",
    emoji: "\u{1F3B5}",
    questName: "Music Forest",
  },
  grab: {
    name: "Grab",
    sector: "Mobility & Super-app",
    description: "Southeast Asia's everyday super-app",
    icon: "G",
    color: "bg-emerald-600",
    emoji: "\u{1F697}",
    questName: "City Rush",
  },
  shopify: {
    name: "Shopify",
    sector: "E-commerce Platform",
    description: "Build your own online store",
    icon: "Sh",
    color: "bg-purple-500",
    emoji: "\u{1F6D2}",
    questName: "Market Square",
  },
  airbnb: {
    name: "Airbnb",
    sector: "Hospitality & Sharing Economy",
    description: "Stay anywhere in the world",
    icon: "A",
    color: "bg-pink-500",
    emoji: "\u{1F3E1}",
    questName: "Travel World",
  },
};

export const challenges: Challenge[] = [
  // ═══════════════════════════════════════════════════════
  // NETFLIX - Streaming Kingdom
  // ═══════════════════════════════════════════════════════
  {
    id: "netflix-1",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Streaming Explorer",
    scenario: "Welcome to Netflix! They have a system that takes in data, processes it, and delivers movies to 300 million people. Help them organize their system!",
    mission: "Drag each item into the right box: is it something that goes IN, gets PROCESSED, or comes OUT?",
    items: [
      { id: "n1", text: "What users like to watch (viewing history)", category: "input" },
      { id: "n2", text: "Live camera feeds from events", category: "input" },
      { id: "n3", text: "Converting videos to different quality levels", category: "processing" },
      { id: "n4", text: "Sending movies to 17,000+ servers worldwide", category: "processing" },
      { id: "n5", text: "300M+ people streaming shows on their devices", category: "output" },
      { id: "n6", text: "Your personal 'Top 10' recommendation list", category: "output" },
    ],
    correctAnswer: { input: ["n1", "n2"], processing: ["n3", "n4"], output: ["n5", "n6"] },
    explanation: "Viewing history and camera feeds are data going IN. Converting and distributing videos is the PROCESSING work. The shows you watch and your recommendations are the OUTPUT delivered to you!",
  },
  {
    id: "netflix-2",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Live Event Helper",
    scenario: "Netflix is streaming a huge boxing match LIVE to 100 million people at the same time! Help sort out how their live streaming system works.",
    mission: "Sort each part of the live streaming system: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "nl1", text: "Raw camera recordings from the boxing arena", category: "input" },
      { id: "nl2", text: "Your phone's screen size and internet speed", category: "input" },
      { id: "nl3", text: "Encoding the live video into streamable format", category: "processing" },
      { id: "nl4", text: "Adjusting video quality based on your connection", category: "processing" },
      { id: "nl5", text: "100M+ devices showing the fight in real-time", category: "output" },
      { id: "nl6", text: "Live quality dashboard for the engineering team", category: "output" },
    ],
    correctAnswer: { input: ["nl1", "nl2"], processing: ["nl3", "nl4"], output: ["nl5", "nl6"] },
    explanation: "Camera recordings and your device info go IN. Encoding and quality adjustment is PROCESSING. The live stream on your device and the dashboard are what comes OUT!",
  },
  {
    id: "netflix-3",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Pipeline Detective",
    scenario: "A new movie just got made! It needs to travel through Netflix's system before you can watch it. But the steps are all mixed up!",
    mission: "Put the steps in the right order \u2014 from movie creation to your screen.",
    steps: [
      { id: "ns1", text: "Movie creators upload their film to Netflix", order: 1 },
      { id: "ns2", text: "The film is converted into many quality levels (4K, HD, SD)", order: 2 },
      { id: "ns3", text: "Copies are sent to servers all around the world", order: 3 },
      { id: "ns4", text: "You hit play \u2014 Netflix detects your device and internet speed", order: 4 },
      { id: "ns5", text: "The best quality version streams to your screen", order: 5 },
    ],
    correctAnswer: ["ns1", "ns2", "ns3", "ns4", "ns5"],
    explanation: "The journey: Upload (Input) \u2192 Convert quality \u2192 Distribute to servers (Processing) \u2192 You press play \u2192 Best version streams to you (Output). Each step builds on the one before!",
  },
  {
    id: "netflix-4",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Tech Sorter",
    scenario: "Netflix uses lots of different things to run their service. Some are specific apps/tools, some are types of technology, and some are business ideas. Can you sort them?",
    mission: "Drag each item: is it a specific TOOL, a TYPE OF TECHNOLOGY, or a BUSINESS IDEA?",
    items: [
      { id: "nc1", text: "AWS MediaLive (live video app)", category: "tool" },
      { id: "nc2", text: "Open Connect servers (Netflix's own hardware)", category: "tool" },
      { id: "nc3", text: "Cloud computing (renting servers online)", category: "technology" },
      { id: "nc4", text: "Copying content to multiple locations at once", category: "technology" },
      { id: "nc5", text: "More users = better recommendations for everyone", category: "business" },
      { id: "nc6", text: "Saving money by owning their own delivery network", category: "business" },
    ],
    correctAnswer: { tool: ["nc1", "nc2"], technology: ["nc3", "nc4"], business: ["nc5", "nc6"] },
    explanation: "Tools are specific software or hardware you can name (MediaLive, Open Connect). Technology is a general approach (cloud computing, content copying). Business ideas are strategies for making money or growing (network effects, cost savings).",
  },
  {
    id: "netflix-5",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "System Mapper",
    scenario: "Netflix has many parts working together. Each part plays a specific role. Can you match them correctly?",
    mission: "Connect each Netflix part on the left to what it does on the right.",
    pairs: [
      { id: "nm1", left: "38 million events collected every second", right: "Input: Raw data flowing into the system" },
      { id: "nm2", left: "Kafka message streaming system", right: "Processing: Moving data between services" },
      { id: "nm3", left: "Content delivery network (CDN) caching", right: "Processing: Storing copies closer to viewers" },
      { id: "nm4", left: "Your personalized Netflix homepage", right: "Output: The final result you see and use" },
      { id: "nm5", left: "What you've watched and liked before", right: "Input: Your personal data feeding the system" },
    ],
    correctAnswer: { nm1: "nm1", nm2: "nm2", nm3: "nm3", nm4: "nm4", nm5: "nm5" },
    explanation: "Events and your watch history are Inputs (data going in). Kafka and CDN caching are Processing (transforming and moving data). Your homepage is the Output (what you actually see).",
  },
  {
    id: "netflix-6",
    sector: "Entertainment & Media",
    company: "Netflix",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Number Cruncher",
    scenario: "Netflix has 300 million subscribers. During evening peak hours, 5% of all subscribers watch at the same time. Each person's stream needs 5 Mbps of internet bandwidth.",
    mission: "How much total bandwidth does Netflix need during peak hours? (answer in Tbps \u2014 terabits per second)",
    calcData: {
      prompt: "Calculate Netflix's peak bandwidth",
      hints: ["300 million \u00D7 5% = how many watching at once?", "Multiply watchers \u00D7 5 Mbps each", "1,000,000 Mbps = 1 Tbps"],
      answer: 75,
      unit: "Tbps",
      tolerance: 2,
    },
    correctAnswer: 75,
    explanation: "300M \u00D7 5% = 15 million watching at once. 15M \u00D7 5 Mbps = 75,000,000 Mbps = 75 Tbps. That's a LOT of bandwidth \u2014 that's why Netflix built their own delivery network!",
  },

  // ═══════════════════════════════════════════════════════
  // SPOTIFY - Music Forest
  // ═══════════════════════════════════════════════════════
  {
    id: "spotify-1",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Music Explorer",
    scenario: "Spotify knows what music you'll love before you do! They use a smart system to recommend songs. Help organize how it works!",
    mission: "Sort each part: does it go IN, get PROCESSED, or come OUT?",
    items: [
      { id: "s1", text: "Songs you've played, skipped, and saved", category: "input" },
      { id: "s2", text: "Audio features of every song (tempo, energy, mood)", category: "input" },
      { id: "s3", text: "Finding users with similar music taste as you", category: "processing" },
      { id: "s4", text: "AI analyzing the actual sound of songs", category: "processing" },
      { id: "s5", text: "Your personal Discover Weekly playlist", category: "output" },
      { id: "s6", text: "AI DJ that talks to you and plays music", category: "output" },
    ],
    correctAnswer: { input: ["s1", "s2"], processing: ["s3", "s4"], output: ["s5", "s6"] },
    explanation: "Your listening history and song features are data going IN. Finding similar users and AI analysis is PROCESSING. Discover Weekly and the AI DJ are what comes OUT for you to enjoy!",
  },
  {
    id: "spotify-2",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Playlist Builder",
    scenario: "Spotify creates custom playlists just for you every week! Let's understand how they build them.",
    mission: "Classify each step: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "sp1", text: "Your saved songs and playlists", category: "input" },
      { id: "sp2", text: "Music blog posts and reviews about artists", category: "input" },
      { id: "sp3", text: "AI learning system improving over time", category: "processing" },
      { id: "sp4", text: "Reading and understanding text about music", category: "processing" },
      { id: "sp5", text: "Daily Mix playlists customized for you", category: "output" },
      { id: "sp6", text: "Release Radar with new songs you'll like", category: "output" },
    ],
    correctAnswer: { input: ["sp1", "sp2"], processing: ["sp3", "sp4"], output: ["sp5", "sp6"] },
    explanation: "Your saved songs and blog reviews are Inputs (raw information). AI learning and text understanding are Processing (making sense of data). Daily Mix and Release Radar are Outputs (personalized playlists for you)!",
  },
  {
    id: "spotify-3",
    sector: "Music Streaming",
    company: "Spotify",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Song Scout",
    scenario: "A new Thai artist just uploaded their very first song to Spotify \u2014 zero plays so far! How does Spotify figure out who should hear it?",
    mission: "Put the steps in order: from upload to appearing in someone's playlist.",
    steps: [
      { id: "ss1", text: "New song gets uploaded to Spotify with its title and genre", order: 1 },
      { id: "ss2", text: "AI listens to the song and measures tempo, energy, and mood", order: 2 },
      { id: "ss3", text: "System reads the song's description, genre tags, and artist info", order: 3 },
      { id: "ss4", text: "Song gets matched with users who like similar-sounding music", order: 4 },
      { id: "ss5", text: "Song shows up in those users' Discover Weekly playlist", order: 5 },
    ],
    correctAnswer: ["ss1", "ss2", "ss3", "ss4", "ss5"],
    explanation: "Upload (Input) \u2192 AI analyzes the sound + reads the text (Processing) \u2192 Matches with right listeners \u2192 Appears in playlists (Output). This is how new artists get discovered even with zero fans!",
  },
  {
    id: "spotify-4",
    sector: "Music Streaming",
    company: "Spotify",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Category Master",
    scenario: "Spotify uses many different things to work. Sort them into the right category!",
    mission: "Is each item a specific TOOL, a TYPE OF TECHNOLOGY, or a BUSINESS IDEA?",
    items: [
      { id: "sc1", text: "Spotify mobile app and web player", category: "tool" },
      { id: "sc2", text: "Spotify for Artists dashboard", category: "tool" },
      { id: "sc3", text: "AI that recognizes patterns in sound waves", category: "technology" },
      { id: "sc4", text: "Computer reading and understanding written text", category: "technology" },
      { id: "sc5", text: "Making everything personal for each user", category: "business" },
      { id: "sc6", text: "Free version that upgrades to paid Premium", category: "business" },
    ],
    correctAnswer: { tool: ["sc1", "sc2"], technology: ["sc3", "sc4"], business: ["sc5", "sc6"] },
    explanation: "Tools are apps you can use (mobile app, artist dashboard). Technology is the science behind it (AI sound recognition, text understanding). Business ideas are strategies (personalization, freemium model).",
  },
  {
    id: "spotify-5",
    sector: "Music Streaming",
    company: "Spotify",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "AI Connector",
    scenario: "Spotify uses different AI techniques for different jobs. Match each technique to what it actually does!",
    mission: "Connect each AI method to its real purpose.",
    pairs: [
      { id: "sm1", left: "Collaborative Filtering", right: "Finds people with similar taste to recommend songs" },
      { id: "sm2", left: "Audio Analysis AI", right: "Listens to the actual sound of songs for patterns" },
      { id: "sm3", left: "Text Mining", right: "Reads blog posts and reviews to learn about music" },
      { id: "sm4", left: "Learning System (BaRT)", right: "Gets better at recommending by learning from mistakes" },
      { id: "sm5", left: "Feature Extraction", right: "Measures specific qualities like tempo, energy, mood" },
    ],
    correctAnswer: { sm1: "sm1", sm2: "sm2", sm3: "sm3", sm4: "sm4", sm5: "sm5" },
    explanation: "Each AI tool has a specific job: finding similar users, analyzing audio, reading text, learning over time, and measuring song qualities. Together they create amazing recommendations!",
  },
  {
    id: "spotify-6",
    sector: "Music Streaming",
    company: "Spotify",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Data Detective",
    scenario: "Spotify has 600 million total users. 40% of them actually use the app each month. Each active user listens to about 25 songs per day.",
    mission: "How many total songs are played per day across all active users? (answer in millions)",
    calcData: {
      prompt: "Calculate total daily song plays",
      hints: ["600 million \u00D7 40% = active users", "Active users \u00D7 25 songs = daily plays"],
      answer: 6000,
      unit: "million songs",
      tolerance: 50,
    },
    correctAnswer: 6000,
    explanation: "600M \u00D7 40% = 240 million active users. 240M \u00D7 25 songs = 6,000 million (6 billion!) songs played every single day. That's the massive Input data that feeds Spotify's recommendation system!",
  },

  // ═══════════════════════════════════════════════════════
  // GRAB - City Rush
  // ═══════════════════════════════════════════════════════
  {
    id: "grab-1",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Ride Guide",
    scenario: "You need a ride in Bangkok! Grab's app connects you with a driver in seconds. Let's see how the ride system works behind the scenes.",
    mission: "Sort each part: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "g1", text: "Your pickup location and where you want to go", category: "input" },
      { id: "g2", text: "GPS location of every nearby driver", category: "input" },
      { id: "g3", text: "Finding the best driver match for you", category: "processing" },
      { id: "g4", text: "Calculating the fastest route to your destination", category: "processing" },
      { id: "g5", text: "Your ride is complete and payment goes through", category: "output" },
      { id: "g6", text: "Trip receipt and 'Rate your driver' screen", category: "output" },
    ],
    correctAnswer: { input: ["g1", "g2"], processing: ["g3", "g4"], output: ["g5", "g6"] },
    explanation: "Your request and driver locations go IN. Finding matches and route planning is PROCESSING. The completed ride and receipt come OUT. Simple as that!",
  },
  {
    id: "grab-2",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Food Delivery Fan",
    scenario: "Hungry? GrabFood delivers meals from your favorite restaurants! Let's trace how a food order flows through the system.",
    mission: "Classify each step: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "gf1", text: "Your food order and any special requests", category: "input" },
      { id: "gf2", text: "Restaurant menu with prices and available items", category: "input" },
      { id: "gf3", text: "Assigning a driver and estimating cooking time", category: "processing" },
      { id: "gf4", text: "Planning the delivery route and arrival time", category: "processing" },
      { id: "gf5", text: "Hot food arriving at your door", category: "output" },
      { id: "gf6", text: "Order tracking showing driver on the map", category: "output" },
    ],
    correctAnswer: { input: ["gf1", "gf2"], processing: ["gf3", "gf4"], output: ["gf5", "gf6"] },
    explanation: "Your order and the menu are Inputs (data going in). Driver assignment and route planning are Processing (the system working). Delivered food and tracking are Outputs (value you receive)!",
  },
  {
    id: "grab-3",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Algorithm Apprentice",
    scenario: "You just opened Grab and requested a ride. A LOT happens in just a few seconds! Put the steps in order.",
    mission: "Arrange what happens from the moment you tap 'Book' to ride complete.",
    steps: [
      { id: "gs1", text: "You enter where you are and where you're going", order: 1 },
      { id: "gs2", text: "The system checks 50+ nearby drivers instantly", order: 2 },
      { id: "gs3", text: "Best driver is picked based on distance and rating", order: 3 },
      { id: "gs4", text: "Driver follows the fastest route to pick you up", order: 4 },
      { id: "gs5", text: "Ride done! Payment handled automatically via GrabPay", order: 5 },
    ],
    correctAnswer: ["gs1", "gs2", "gs3", "gs4", "gs5"],
    explanation: "Your request (Input) \u2192 System checks drivers \u2192 Best match assigned (Processing) \u2192 Pickup and ride \u2192 Payment complete (Output). All of this happens in seconds!",
  },
  {
    id: "grab-4",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Super-app Sorter",
    scenario: "Grab does SO many things \u2014 rides, food, payments, and more. Sort their different parts into categories!",
    mission: "Is each item a specific TOOL, a TYPE OF TECHNOLOGY, or a BUSINESS IDEA?",
    items: [
      { id: "gc1", text: "Grab mobile app (for riders and drivers)", category: "tool" },
      { id: "gc2", text: "GrabPay digital wallet", category: "tool" },
      { id: "gc3", text: "Real-time GPS tracking on maps", category: "technology" },
      { id: "gc4", text: "Cloud servers that scale up when busy", category: "technology" },
      { id: "gc5", text: "Connecting riders with drivers (two-sided market)", category: "business" },
      { id: "gc6", text: "One app for rides, food, payments, and more", category: "business" },
    ],
    correctAnswer: { tool: ["gc1", "gc2"], technology: ["gc3", "gc4"], business: ["gc5", "gc6"] },
    explanation: "Tools are specific apps you can touch (Grab app, GrabPay). Technology is the system powering it (GPS, cloud servers). Business ideas are the big strategies (marketplace model, super-app approach).",
  },
  {
    id: "grab-5",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Strategy Connector",
    scenario: "Grab offers many different services. Each one uses a smart business strategy. Match them up!",
    mission: "Connect each Grab service to the business idea behind it.",
    pairs: [
      { id: "gm1", left: "GrabCar (ride-hailing)", right: "Connecting riders and drivers in a marketplace" },
      { id: "gm2", left: "GrabFood (delivery)", right: "Expanding from rides into food delivery" },
      { id: "gm3", left: "GrabPay (digital wallet)", right: "Keeping users in the Grab money ecosystem" },
      { id: "gm4", left: "GrabMart (grocery delivery)", right: "Adding more types of delivery services" },
      { id: "gm5", left: "GrabRewards (loyalty points)", right: "Keeping customers coming back with rewards" },
    ],
    correctAnswer: { gm1: "gm1", gm2: "gm2", gm3: "gm3", gm4: "gm4", gm5: "gm5" },
    explanation: "Each Grab service has a clear business strategy: marketplace model, market expansion, ecosystem lock-in, service diversification, and customer retention. That's how super-apps grow!",
  },
  {
    id: "grab-6",
    sector: "Mobility & Super-app",
    company: "Grab",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Growth Analyst",
    scenario: "Grab has 200 million registered users across 8 countries. 30% of them use the app at least once a week. Each active user takes about 2 trips per week.",
    mission: "How many total trips happen each week? (answer in millions)",
    calcData: {
      prompt: "Calculate weekly trips across all countries",
      hints: ["200 million \u00D7 30% = weekly active users", "Active users \u00D7 2 trips = total weekly trips"],
      answer: 120,
      unit: "million trips",
      tolerance: 5,
    },
    correctAnswer: 120,
    explanation: "200M \u00D7 30% = 60 million active users per week. 60M \u00D7 2 trips = 120 million trips every week! Each trip is an Output of Grab's system, starting from a ride request Input.",
  },

  // ═══════════════════════════════════════════════════════
  // SHOPIFY - Market Square
  // ═══════════════════════════════════════════════════════
  {
    id: "shopify-1",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Store Builder",
    scenario: "A small business owner wants to sell handmade jewelry online. They sign up for Shopify. Let's see how the platform works!",
    mission: "Sort each part: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "sh1", text: "Product photos, descriptions, and prices from the seller", category: "input" },
      { id: "sh2", text: "Customer orders and payment details", category: "input" },
      { id: "sh3", text: "Running the store across 100+ connected systems", category: "processing" },
      { id: "sh4", text: "Processing 66 million messages per second internally", category: "processing" },
      { id: "sh5", text: "40,000 completed purchases every minute at peak", category: "output" },
      { id: "sh6", text: "$292 billion worth of products sold in a year", category: "output" },
    ],
    correctAnswer: { input: ["sh1", "sh2"], processing: ["sh3", "sh4"], output: ["sh5", "sh6"] },
    explanation: "Product listings and orders are Inputs (data entering). Running systems and message processing are Processing (the work being done). Completed purchases and sales volume are Outputs (results delivered)!",
  },
  {
    id: "shopify-2",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Black Friday Hero",
    scenario: "It's Black Friday \u2014 the biggest shopping day of the year! Millions of people are buying at the same time. Let's see what happens when you click 'Buy Now'.",
    mission: "Classify each step: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "sb1", text: "Items in your shopping cart", category: "input" },
      { id: "sb2", text: "Your credit card number and address", category: "input" },
      { id: "sb3", text: "Checking if the payment is real (fraud detection)", category: "processing" },
      { id: "sb4", text: "Checking if the item is still in stock", category: "processing" },
      { id: "sb5", text: "Order confirmation email in your inbox", category: "output" },
      { id: "sb6", text: "Shipping label printed and ready to go", category: "output" },
    ],
    correctAnswer: { input: ["sb1", "sb2"], processing: ["sb3", "sb4"], output: ["sb5", "sb6"] },
    explanation: "Your cart and payment info are Inputs. Fraud checking and inventory verification are Processing. The confirmation email and shipping label are Outputs \u2014 the valuable results!",
  },
  {
    id: "shopify-3",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Order Tracker",
    scenario: "On Black Friday, Shopify handles 284 million requests every minute! When someone clicks 'Buy Now', many things happen in milliseconds. Put them in order!",
    mission: "Arrange what happens from clicking 'Buy' to getting your confirmation.",
    steps: [
      { id: "so1", text: "Customer clicks 'Buy Now' on the store", order: 1 },
      { id: "so2", text: "Request gets sent to the right server automatically", order: 2 },
      { id: "so3", text: "System checks if item is in stock and payment is valid", order: 3 },
      { id: "so4", text: "Order info is sent to shipping, email, and accounting services", order: 4 },
      { id: "so5", text: "Customer gets confirmation; package starts being prepared", order: 5 },
    ],
    correctAnswer: ["so1", "so2", "so3", "so4", "so5"],
    explanation: "Click Buy (Input) \u2192 Route to server \u2192 Verify stock & payment \u2192 Notify all services (Processing) \u2192 Confirmation sent (Output). All in milliseconds during the busiest day of the year!",
  },
  {
    id: "shopify-4",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Platform Organizer",
    scenario: "Shopify uses many parts to power millions of online stores. Sort them into the right category!",
    mission: "Is each item a specific TOOL, a TYPE OF TECHNOLOGY, or a BUSINESS IDEA?",
    items: [
      { id: "scc1", text: "Shopify Markets (selling to other countries)", category: "tool" },
      { id: "scc2", text: "Shopify POS (in-store checkout system)", category: "tool" },
      { id: "scc3", text: "Splitting the workload across 100+ separate systems", category: "technology" },
      { id: "scc4", text: "Message streaming to connect all services", category: "technology" },
      { id: "scc5", text: "Making it easy for anyone to start an online store", category: "business" },
      { id: "scc6", text: "Charging monthly fees for the platform service", category: "business" },
    ],
    correctAnswer: { tool: ["scc1", "scc2"], technology: ["scc3", "scc4"], business: ["scc5", "scc6"] },
    explanation: "Tools are specific products (Markets app, POS system). Technology is how the system works (load splitting, message streaming). Business ideas are the strategies (lowering barriers, subscription model).",
  },
  {
    id: "shopify-5",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Architecture Guide",
    scenario: "Shopify's system has many specialized parts. Each one does a specific job. Match them up!",
    mission: "Connect each system part to what it does.",
    pairs: [
      { id: "smm1", left: "Database (stores all data)", right: "Saves product info, orders, and customer details permanently" },
      { id: "smm2", left: "Fast memory cache", right: "Keeps frequently used data ready for instant access" },
      { id: "smm3", left: "Message streaming system", right: "Routes order events to different services automatically" },
      { id: "smm4", left: "Traffic distributor", right: "Spreads incoming visitors across multiple servers evenly" },
      { id: "smm5", left: "Object storage layer", right: "Stores product images and files for quick retrieval" },
    ],
    correctAnswer: { smm1: "smm1", smm2: "smm2", smm3: "smm3", smm4: "smm4", smm5: "smm5" },
    explanation: "Each part has a unique job: database for storage, cache for speed, message system for communication, traffic distributor for balance, and object storage for files. They all work together!",
  },
  {
    id: "shopify-6",
    sector: "E-commerce Platform",
    company: "Shopify",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Scale Calculator",
    scenario: "Shopify has 5.6 million store owners worldwide. Each store lists an average of 50 products for sale.",
    mission: "How many total products are listed on Shopify? (answer in millions)",
    calcData: {
      prompt: "Calculate total product listings on Shopify",
      hints: ["5.6 million stores \u00D7 50 products each", "This is the total Input data the platform manages"],
      answer: 280,
      unit: "million products",
      tolerance: 10,
    },
    correctAnswer: 280,
    explanation: "5.6M stores \u00D7 50 products = 280 million product listings! Each listing is an Input that Shopify must process (show to buyers, manage inventory, handle orders) to create Output (completed sales).",
  },

  // ═══════════════════════════════════════════════════════
  // AIRBNB - Travel World
  // ═══════════════════════════════════════════════════════
  {
    id: "airbnb-1",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Travel Planner",
    scenario: "Planning a trip to Chiang Mai! Airbnb connects you with local hosts who rent out their homes. Let's see how the platform organizes everything.",
    mission: "Sort each part: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "a1", text: "8 million+ homes listed by hosts worldwide", category: "input" },
      { id: "a2", text: "Your search: dates, location, number of guests", category: "input" },
      { id: "a3", text: "Ranking and sorting listings by best match", category: "processing" },
      { id: "a4", text: "Running the platform on cloud servers", category: "processing" },
      { id: "a5", text: "Confirmed booking with secure payment", category: "output" },
      { id: "a6", text: "Safety verification results for host and guest", category: "output" },
    ],
    correctAnswer: { input: ["a1", "a2"], processing: ["a3", "a4"], output: ["a5", "a6"] },
    explanation: "Listings and your search are Inputs (data going in). Ranking and server processing are Processing (the work). Confirmed bookings and safety results are Outputs (value created)!",
  },
  {
    id: "airbnb-2",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-ipo",
    difficulty: "easy",
    points: 100,
    role: "Booking Assistant",
    scenario: "A guest from Tokyo wants to book a villa in Bali! Money needs to be converted, identity verified, and the host notified. Let's trace the booking flow.",
    mission: "Classify each step: INPUT, PROCESSING, or OUTPUT?",
    items: [
      { id: "ab1", text: "Guest selects dates and number of travelers", category: "input" },
      { id: "ab2", text: "Host's pricing and available dates", category: "input" },
      { id: "ab3", text: "Calculating total price with fees and currency exchange", category: "processing" },
      { id: "ab4", text: "Verifying guest's identity and checking for fraud", category: "processing" },
      { id: "ab5", text: "Both host and guest get booking confirmation", category: "output" },
      { id: "ab6", text: "Payment safely held until guest checks in", category: "output" },
    ],
    correctAnswer: { input: ["ab1", "ab2"], processing: ["ab3", "ab4"], output: ["ab5", "ab6"] },
    explanation: "Guest preferences and host pricing are Inputs. Price calculation and identity checks are Processing. Confirmations and held payments are Outputs!",
  },
  {
    id: "airbnb-3",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "ordering",
    difficulty: "medium",
    points: 150,
    role: "Journey Mapper",
    scenario: "From searching for a place to leaving a review \u2014 put the complete Airbnb guest journey in order!",
    mission: "Arrange the guest experience from start to finish.",
    steps: [
      { id: "as1", text: "Guest searches for a place using filters (price, location, dates)", order: 1 },
      { id: "as2", text: "System ranks listings by relevance, reviews, and quality", order: 2 },
      { id: "as3", text: "Guest picks a listing and sends a booking request", order: 3 },
      { id: "as4", text: "Payment is processed and host is notified", order: 4 },
      { id: "as5", text: "Guest stays and leaves a review afterward", order: 5 },
    ],
    correctAnswer: ["as1", "as2", "as3", "as4", "as5"],
    explanation: "Search (Input) \u2192 System ranks options (Processing) \u2192 Pick and book \u2192 Payment processed (Processing) \u2192 Stay and review (Output). Fun fact: that review becomes Input for future guests!",
  },
  {
    id: "airbnb-4",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "drag-drop-classify",
    difficulty: "medium",
    points: 150,
    role: "Platform Sorter",
    scenario: "Airbnb has tools, technologies, and business strategies. Sort them into the right category!",
    mission: "Is each item a specific TOOL, a TYPE OF TECHNOLOGY, or a BUSINESS IDEA?",
    items: [
      { id: "ac1", text: "Airbnb mobile app and website", category: "tool" },
      { id: "ac2", text: "Secure online payment system", category: "tool" },
      { id: "ac3", text: "Cloud servers that run the platform", category: "technology" },
      { id: "ac4", text: "Small independent services working together", category: "technology" },
      { id: "ac5", text: "Connecting hosts who have rooms with guests who need them", category: "business" },
      { id: "ac6", text: "Building trust through ratings and reviews", category: "business" },
    ],
    correctAnswer: { tool: ["ac1", "ac2"], technology: ["ac3", "ac4"], business: ["ac5", "ac6"] },
    explanation: "Tools are what users touch (app, payment system). Technology is the infrastructure (cloud servers, microservices). Business ideas are the strategies (marketplace model, trust through reviews).",
  },
  {
    id: "airbnb-5",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "matching",
    difficulty: "hard",
    points: 200,
    role: "Trust Builder",
    scenario: "Trust is EVERYTHING for Airbnb \u2014 you're staying in a stranger's home! Match each trust feature to its category.",
    mission: "Connect each trust feature to what type of thing it is.",
    pairs: [
      { id: "am1", left: "Review and rating system in the app", right: "Tool: A feature users can see and use directly" },
      { id: "am2", left: "Encrypted secure payment processing", right: "Technology: Security system working behind the scenes" },
      { id: "am3", left: "ID verification using AI", right: "Technology: Automated identity checking" },
      { id: "am4", left: "Community trust that makes people feel safe booking", right: "Business idea: Trust as a competitive advantage" },
      { id: "am5", left: "Superhost badge for top-rated hosts", right: "Business idea: Rewarding quality to encourage better service" },
    ],
    correctAnswer: { am1: "am1", am2: "am2", am3: "am3", am4: "am4", am5: "am5" },
    explanation: "The review system is a visible Tool. Encryption and AI verification are hidden Technologies. Community trust and Superhost badges are Business ideas that give Airbnb an advantage over hotels!",
  },
  {
    id: "airbnb-6",
    sector: "Hospitality & Sharing Economy",
    company: "Airbnb",
    type: "calculation",
    difficulty: "hard",
    points: 200,
    role: "Market Analyst",
    scenario: "Airbnb has 8 million property listings worldwide. On average, these properties are booked 50% of the available days in a year (365 days).",
    mission: "How many total guest-nights are booked per year? (answer in millions)",
    calcData: {
      prompt: "Calculate annual guest-nights booked",
      hints: ["8 million listings \u00D7 50% occupancy", "Multiply by 365 days per year", "Answer in millions"],
      answer: 1460,
      unit: "million guest-nights",
      tolerance: 50,
    },
    correctAnswer: 1460,
    explanation: "8M listings \u00D7 50% \u00D7 365 days = 1,460 million guest-nights per year! Each night booked is an Output of the platform, created from host listing Inputs processed by Airbnb's booking system.",
  },
];
